apiVersion: v1
kind: Service
metadata:
  name: observatoriequitat-web
  labels:
    app: observatoriequitat-web
spec:
  selector:
    app: observatoriequitat-web
  type: ClusterIP
  ports:
    - name: http
      port: 80
