update-web-api:
	yarn remove web-api-v2
	yarn add git+https://e8a5ce007f5ea25137792bb563618650fb274de9:x-oauth-basic@github.com/AjManresa/web-api-v2.git
update-web-fields:
	yarn remove web-fields-v2
	yarn add git+https://e8a5ce007f5ea25137792bb563618650fb274de9:x-oauth-basic@github.com/AjManresa/web-fields-v2.git
update-web-app:
	yarn remove web-app-v2
	yarn add git+https://e8a5ce007f5ea25137792bb563618650fb274de9:x-oauth-basic@github.com/AjManresa/web-app-v2.git
update-all: update-web-api update-web-fields update-web-app


