FROM eu.gcr.io/websmunicipals/base-web:devel-v1

COPY apache2/default.conf /etc/apache2/sites-enabled/000-default.conf

RUN ln -s /var/www/html/web/webs/default /var/www/html/web/assets-default

RUN ln -s /var/www/html/web /var/www/html/observatoriequitat
RUN mkdir /var/www/html/web/webs/observatoriequitat
RUN ln -s /var/www/html/web/webs/observatoriequitat /var/www/html/web/assets